apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "sshd.fullname" . }}
  labels:
    app: {{ include "sshd.name" . }}
    chart: {{ include "sshd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "sshd.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "sshd.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
            - name: docker-graph-storage
              emptyDir: {}
      {{- if $.Values.gcpSecretName }}
            - name: gcp-secret
              secret:
                secretName: {{ .Values.gcpSecretName }}
      {{- end }}
{{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      dnsConfig:
{{ toYaml .Values.dnsConfig | indent 8 }}
{{- end }}
      containers:
        - name: dind
          image: "{{ .Values.dind.image.repository }}:{{ .Values.dind.image.tag }}"
          imagePullPolicy: {{ .Values.dind.image.pullPolicy }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: docker-graph-storage
              mountPath: /var/lib/docker
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
           - name: DOCKER_HOST
             value: tcp://localhost:2375
          ports:
            - name: sshd
              containerPort: 22
              protocol: TCP
          securityContext:
{{ toYaml .Values.securityContext | indent 12 }}
          volumeMounts:
         {{- if .Values.gcpSecretName }}
                - name: gcp-secret
                  mountPath: "/license"
        {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
